### ISSUE TITLE
Compare budget and expenditure

### ISSUE THREAD

**Issue by gangadevib** [CS4244/Where2Go#3]
Compare budget with expenditure and eliminate countries or if only one left, inform user

**Comment by Dauth** [comment]
1) Precompute and include the various countries expenditure in the destination template
2) create a filter which checks if user's budget is less than expenditure

Note: i need to know what you meant for calculateExpense, i edited the LHS for both desired instead of one of each (destination and desired)

**Comment by gangadevib** [comment]
1) We can only compute the expenditure for each destination only after the user specifies his number of days spent in the holiday destination. 

Prospective expenditure = prospective amt that can be spent in a country in a day x amt of days spend

The filter will check the prospective expenditure of each country with the user's specified budget and will then remove countries which is not within user's budget. Also if no countries are found to be within user's budget, halt and report to user, i.e. 10 days with a budget of $50 -> no countries as each country will require at least a budget of $100 per day.

**Comment by Dauth** [comment]
fireBudgetFilter has been added to solve this issue
